### ISSUE TITLE
Milestones: Part 2

### ISSUE THREAD

**Issue by RobbieGoldfarb** [Brevada/brv#112]
# Back-end
- Work required for this interface
- For each related aspect show the % change
# Front-end
- New tab
- Duration / # responses required before we start displaying data here (put message - ‘not enough time has passed / not enough responses have received)
- responses required = should be a number based on their rating frequency (differs for each company)
- For each related aspect show the % change
- total average from before you start vs. average since the milestone
- Option to change related aspects
- Disclaimer and wording decisions 
- Explain how calculations are decided
- Option to disregard milestone

**Comment by noahnu** [comment]
Outdated, although some of the points are still valid. Closed for now (should probably be re-submitted with individual issues).
