### ISSUE TITLE
Make Better Use of Space on Tablet App

### ISSUE THREAD

**Issue by zacharyzobary** [Brevada/brv#123]
@RobbieGoldfarb @noahnu 

Right now the arbitrarily chosen fab 5 "default" aspects (taste, food quality, price, customer service, ambience) do not all fit on the screen at once. I think they should but this is obviously a debate. I think we can make better use of space and fit all 5 main aspects in on one screen comfortably.

**Comment by noahnu** [comment]
Interestingly more relevant; although in a different capacity.
