### ISSUE TITLE
Issue Locking The Tablet App

### ISSUE THREAD

**Issue by zacharyzobary** [Brevada/brv#169]
@noahnu @RobbieGoldfarb 

When exiting the tablet app by hitting the back button 10 times, it can sometimes be difficult to relock the tablet app. Last time I was at Ali Baba, I was able to lock the tablet app with regards to the settings button, but the home page button (bottom center) was not allowing me to lock the tablet app (no selection of Brevada tablet app always).

**Comment by noahnu** [comment]
Revisiting now. Will reference & close this issue once resolved.

**Comment by noahnu** [comment]
Yes, new version should fix this.
